Repository amczuboka/Decagon-CondoManagementSystem, pull requests merged in 2024-04, with the labels that each got.

#199 Fixed my employees cypress test
  cypress/e2e/MyEmployees.cy.ts
  src/app/components/header/header.component.html
  src/app/pages/add-new-property/add-new-property.component.html
Labels: bug, enhancement

#200 #192 #193 Requests Follow-Up and Modifications
  src/app/models/users.ts
  src/app/pages/building-info/condo/condo.component.spec.ts
  src/app/pages/building-info/condo/condo.component.ts
  src/app/pages/building-info/locker/locker.component.spec.ts
  src/app/pages/building-info/locker/locker.component.ts
  src/app/pages/building-info/parking-spot/parking-spot.component.spec.ts
  src/app/pages/building-info/parking-spot/parking-spot.component.ts
  src/app/pages/notifications/notifications.component.html
  src/app/pages/notifications/notifications.component.scss
  src/app/pages/notifications/notifications.component.spec.ts
  src/app/pages/notifications/notifications.component.ts
  src/app/pages/request-page/request-page.component.spec.ts
  src/app/pages/request-page/request-page.component.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
Labels: enhancement, back-end, front-end

#207 61 budget report
  cypress/e2e/BudgetReport.cy.ts
  src/app/app-routing.module.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/pages/building-info/budget-report/budget-report.component.html
  src/app/pages/building-info/budget-report/budget-report.component.spec.ts
  src/app/pages/building-info/budget-report/budget-report.component.ts
Labels: back-end

#208 Fixed Cypress test 116
  cypress/e2e/Building-Overview.cy.ts
  cypress/e2e/CreateBuilding.cy.ts
  cypress/e2e/utils.cy.ts
  src/app/services/building.service.ts
Labels: bug, Testing

#210 Booking back end
  src/app/components/building/building.component.scss
  src/app/components/footer/footer.component.html
  src/app/components/header/header.component.html
  src/app/models/properties.ts
  src/app/models/users.ts
  src/app/pages/building-info/bookings/booking-card/booking-card.component.html
  src/app/pages/building-info/bookings/booking-card/booking-card.component.scss
  src/app/pages/building-info/bookings/booking-card/booking-card.component.spec.ts
  src/app/pages/building-info/bookings/booking-card/booking-card.component.ts
  src/app/pages/building-info/bookings/bookings.component.html
  src/app/pages/building-info/bookings/bookings.component.spec.ts
  src/app/pages/building-info/bookings/bookings.component.ts
  src/app/pages/building-info/building-info.component.html
  src/app/pages/building-info/building-overview/building-overview.component.html
  src/app/pages/building-info/building-overview/building-overview.component.ts
  src/app/pages/building-info/locker/locker.component.html
  src/app/pages/building-info/schedule/schedule.component.spec.ts
  src/app/pages/building-info/schedule/schedule.component.ts
  src/app/services/bookings.service.spec.ts
  src/app/services/bookings.service.ts
  src/app/services/building.service.spec.ts
Labels: back-end

#217 Added my-employees button back
  src/app/components/header/header.component.ts
Labels: bug
