Repository amczuboka/Decagon-CondoManagementSystem, pull requests merged in 2024-02, with the labels that each got.

#137 Sprint 1 auth, login, register, profile, unit tests, and acceptance tests
  .github/workflows/ci_tests.yml
  Document/test/testing info.pdf
  angular.json
  cypress/downloads/downloads.htm
  cypress/e2e/TEST.png
  cypress/e2e/default.png
  cypress/e2e/spec.cy.ts
  cypress/e2e/utils.cy.ts
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/footer/footer.component.spec.ts
  src/app/components/footer/footer.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/models/users.ts
  src/app/pages/landing/landing.component.html
  src/app/pages/landing/landing.component.scss
  src/app/pages/landing/landing.component.spec.ts
  src/app/pages/landing/landing.component.ts
  src/app/pages/login/login/login.component.html
  src/app/pages/login/login/login.component.scss
  src/app/pages/login/login/login.component.spec.ts
  src/app/pages/login/login/login.component.ts
  src/app/pages/login/register/register.component.html
  src/app/pages/login/register/register.component.scss
  src/app/pages/login/register/register.component.spec.ts
  src/app/pages/login/register/register.component.ts
  src/app/pages/login/verify-email/verify-email.component.html
  src/app/pages/login/verify-email/verify-email.component.scss
  src/app/pages/login/verify-email/verify-email.component.spec.ts
  src/app/pages/login/verify-email/verify-email.component.ts
  src/app/pages/user-profile/user-profile.component.html
  src/app/pages/user-profile/user-profile.component.scss
  src/app/pages/user-profile/user-profile.component.spec.ts
  src/app/pages/user-profile/user-profile.component.ts
  src/app/services/auth.guard.spec.ts
  src/app/services/auth.guard.ts
  src/app/services/auth.service.spec.ts
  src/app/services/auth.service.ts
  src/app/services/notification.service.spec.ts
  src/app/services/notification.service.ts
  src/app/services/storage.service.spec.ts
  src/app/services/storage.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/assets/imgs/logo/decagon.png
  src/index.html
  src/karma.conf.js
  src/styles.scss
  tsconfig.app.json
  tsconfig.json
Labels: Testing, back-end, front-end

#138 Added risk documentation
  documentation/Risk Assessment documentation/Risk analysis template.xlsx
  documentation/Risk Assessment documentation/Risk assessment and Risk management plan (RMP).pdf
Labels: documentation

#154 Create & Style Condo Component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/condo/condo.component.html
  src/app/components/condo/condo.component.scss
  src/app/components/condo/condo.component.spec.ts
  src/app/components/condo/condo.component.ts
  src/app/components/key-registration/key-registration.component.html
  src/app/components/key-registration/key-registration.component.scss
  src/app/components/key-registration/key-registration.component.spec.ts
  src/app/components/key-registration/key-registration.component.ts
  src/app/models/properties.ts
  src/app/pages/building-info/building-info.component.html
  src/assets/imgs/Condo1.jpg
  src/assets/imgs/Condo2.jpg
Labels: front-end

#155 #41 front end lockers and parkings
  angular.json
  cypress/e2e/LoginAndProfilePage.cy.ts
  src/app/app.module.ts
  src/app/components/building/building.component.html
  src/app/components/building/building.component.scss
  src/app/components/building/building.component.spec.ts
  src/app/components/building/building.component.ts
  src/app/components/condo/condo.component.ts
  src/app/components/header/header.component.scss
  src/app/components/locker/locker.component.html
  src/app/components/locker/locker.component.scss
  src/app/components/locker/locker.component.spec.ts
  src/app/components/locker/locker.component.ts
  src/app/components/parking-spot/parking-spot.component.html
  src/app/components/parking-spot/parking-spot.component.scss
  src/app/components/parking-spot/parking-spot.component.spec.ts
  src/app/components/parking-spot/parking-spot.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.scss
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/models/properties.ts
  src/app/pages/building-info/building-info.component.html
  src/app/pages/landing/landing.component.html
  src/app/pages/landing/landing.component.scss
  src/app/pages/landing/landing.component.spec.ts
  src/assets/imgs/building1.jpg
Labels: front-end

#156 #35 my buildings component
  src/app/components/building/building.component.html
  src/app/components/building/building.component.ts
  src/app/models/properties.ts
Labels: front-end

#158 #49 notifications
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/delete-notification-dialog/delete-notification-dialog.component.html
  src/app/components/delete-notification-dialog/delete-notification-dialog.component.scss
  src/app/components/delete-notification-dialog/delete-notification-dialog.component.spec.ts
  src/app/components/delete-notification-dialog/delete-notification-dialog.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/models/users.ts
  src/app/pages/individual-condo/individual-condo.component.ts
  src/app/pages/landing/landing.component.spec.ts
  src/app/pages/landing/landing.component.ts
  src/app/pages/login/login/login.component.spec.ts
  src/app/pages/login/login/login.component.ts
  src/app/pages/login/register/register.component.spec.ts
  src/app/pages/notifications/notifications.component.html
  src/app/pages/notifications/notifications.component.scss
  src/app/pages/notifications/notifications.component.spec.ts
  src/app/pages/notifications/notifications.component.ts
  src/app/pages/user-profile/user-profile.component.spec.ts
  src/app/pages/user-profile/user-profile.component.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
Labels: back-end, front-end
