Repository amczuboka/Decagon-CondoManagementSystem, pull requests merged in 2024-03, with the labels that each got.

#160 Employees Page Front-End
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/employees-list/employees-list.component.html
  src/app/components/employees-list/employees-list.component.scss
  src/app/components/employees-list/employees-list.component.spec.ts
  src/app/components/employees-list/employees-list.component.ts
  src/app/pages/my-employees/my-employees.component.html
  src/app/pages/my-employees/my-employees.component.scss
  src/app/pages/my-employees/my-employees.component.spec.ts
  src/app/pages/my-employees/my-employees.component.ts
  src/app/services/company.guard.spec.ts
  src/app/services/company.guard.ts
Labels: front-end

#169 Added acceptance tests for notifications
  .github/workflows/ci_tests.yml
  cypress/downloads/downloads.htm
  cypress/e2e/NotificationBarAndPage.cy.ts
  src/app/app-routing.module.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/models/properties.ts
  src/app/pages/individual-condo/condo-features/condo-features.component.spec.ts
  src/app/pages/individual-condo/condo-features/condo-features.component.ts
  src/app/pages/individual-condo/description/description.component.spec.ts
  src/app/pages/individual-condo/description/description.component.ts
  src/app/pages/individual-condo/individual-condo.component.ts
  src/app/services/user.service.ts
Labels: Testing

#180 Request page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/my-employees/employees-list/employees-list.component.ts
  src/app/pages/request-page/request-page.component.html
  src/app/pages/request-page/request-page.component.scss
  src/app/pages/request-page/request-page.component.spec.ts
  src/app/pages/request-page/request-page.component.ts
Labels: front-end

#173 Tasks #102 #32 #33 individual condo
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/building-info/building-info.component.html
  src/app/pages/building-info/condo/condo.component.html
  src/app/pages/building-info/condo/condo.component.scss
  src/app/pages/building-info/condo/condo.component.ts
  src/app/pages/individual-condo/edit-condo-dialog/edit-condo-dialog.component.html
  src/app/pages/individual-condo/edit-condo-dialog/edit-condo-dialog.component.scss
  src/app/pages/individual-condo/edit-condo-dialog/edit-condo-dialog.component.spec.ts
  src/app/pages/individual-condo/edit-condo-dialog/edit-condo-dialog.component.ts
  src/app/pages/individual-condo/individual-condo.component.html
  src/app/pages/individual-condo/individual-condo.component.scss
  src/app/pages/individual-condo/individual-condo.component.spec.ts
  src/app/pages/individual-condo/individual-condo.component.ts
  src/app/pages/individual-condo/user-info/user-info.component.html
  src/app/pages/individual-condo/user-info/user-info.component.spec.ts
  src/app/pages/individual-condo/user-info/user-info.component.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
Labels: back-end, front-end

#181 #148 #149 request unit locker parking (with notifications)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/models/users.ts
  src/app/pages/building-info/building-info.component.html
  src/app/pages/building-info/building-overview/building-overview.component.html
  src/app/pages/building-info/building-overview/building-overview.component.ts
  src/app/pages/building-info/condo/condo.component.html
  src/app/pages/building-info/condo/condo.component.spec.ts
  src/app/pages/building-info/condo/condo.component.ts
  src/app/pages/building-info/locker/locker.component.html
  src/app/pages/building-info/locker/locker.component.spec.ts
  src/app/pages/building-info/locker/locker.component.ts
  src/app/pages/building-info/parking-spot/parking-spot.component.html
  src/app/pages/building-info/parking-spot/parking-spot.component.spec.ts
  src/app/pages/building-info/parking-spot/parking-spot.component.ts
  src/app/pages/individual-condo/edit-condo-dialog/edit-condo-dialog.component.spec.ts
  src/app/pages/individual-condo/individual-condo.component.spec.ts
  src/app/pages/individual-condo/location/location.component.spec.ts
  src/app/pages/my-employees/employees-list/employees-list.component.ts
  src/app/pages/notifications/notifications.component.html
  src/app/pages/notifications/notifications.component.scss
  src/app/pages/notifications/notifications.component.spec.ts
  src/app/pages/notifications/notifications.component.ts
  src/app/pages/request-page/request-page.component.html
  src/app/pages/request-page/request-page.component.scss
  src/app/pages/request-page/request-page.component.spec.ts
  src/app/pages/request-page/request-page.component.ts
  src/app/services/user.service.ts
Labels: bug, back-end, front-end

#186 Added source code documentation comments in services
  src/app/services/auth.guard.ts
  src/app/services/auth.service.ts
  src/app/services/company.guard.ts
  src/app/services/storage.service.ts
  src/app/services/user.service.ts
Labels: documentation

#188 Task: Create acceptance test for Create Profile page for complex building. #45
  cypress/e2e/CreateBuilding.cy.ts
  cypress/e2e/utils.cy.ts
  src/app/app.component.ts
  src/app/components/building/building.component.scss
  src/app/pages/add-new-property/add-condo-dialog/add-condo-dialog.component.html
  src/app/pages/add-new-property/add-locker-dialog/add-locker-dialog.component.html
  src/app/pages/add-new-property/add-new-property.component.ts
  src/app/services/building.service.ts
Labels: Testing

#189 #120 employees page back end
  src/app/components/building/building.component.html
  src/app/components/footer/footer.component.html
  src/app/components/header/header.component.scss
  src/app/pages/my-employees/employees-list/employees-list.component.html
  src/app/pages/my-employees/employees-list/employees-list.component.scss
  src/app/pages/my-employees/employees-list/employees-list.component.spec.ts
  src/app/pages/my-employees/employees-list/employees-list.component.ts
  src/app/services/building.service.spec.ts
  src/app/services/building.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/styles.scss
Labels: back-end
